### PR TITLE
Update kubernetes to 1.6.2

### PR DESCRIPTION
**Pull request by gabrielpjordao**

### CODE REVIEW

**Comment by gabrielpjordao** [comment]
It seems that there are some changes in the code that need to be made in order to make it work. You can ignore this PR for now..

**Comment by mbogus** [comment]
Agreed! There are backwards incompatible changes in kubernetes' client and REST client that need to be investigated first.

**Comment by gabrielpjordao** [comment]
I see.. I'll probably not be able to update it by now. Do you have plans for updating it? Thanks!

**Comment by gabrielpjordao** [comment]
Hey there @mbogus. Can you please take a look at the changes I made?
I forked the docker repo and, from what I could see, it's running smoothly so far. 

As I imagined, the issue https://github.com/mbogus/kube-amqp-autoscale/issues/1 has been fixed with this change as well.

**Comment by mbogus** [comment]
All done now. Thanks for your great work!

**Comment by gabrielpjordao** [comment]
Thanks for the work. :-) Now that we can use it, your work with kube-amqp-autoscale will be very helpful.

**Pull request merged**
